---
functional:
-  Пользователь должен иметь возможность искать товары по ключевому слову или категории
-  Пользователь должен иметь возможность фильтровать товары
-  Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
-  Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
-  Пользователь должен иметь возможность видеть рейтинг товара, а также цену товара со скидкой и без нее
non-functional:
-  Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
-  Сайт должен быть безопасным и защищать данные пользователя
-  Сайт должен иметь мобильную версию
-  Сайт нужно протестировать на совместимость с последними версиями браузеров
-  Важно, чтобы сайт мог обрабатывать большое количество трафика
-  Сайт должен быть доступен на различных устройствах
-  Магазин должен быть SPA-приложением
-  Корзина должна храниться в сессии браузера
implicit:
-  Сайт должен содержать актуальную информацию об остатках товара в магазине
-  Пользователь должен иметь возможность удалять товар из корзины
-  Сайт должен иметь обратную связь с пользователем
-  Пользователь должен иметь возможность связаться с технической поддержкой сайта
-  Пользователь должен иметь возможность переключения языка (русский и английский)
